### ISSUE TITLE
DeadlineExceededError

### ISSUE THREAD

**Issue by kercos** [kercos/PickMeUp#13]
In certain situation, especially in broadcasting messages this error occurs.
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded
See https://cloud.google.com/appengine/articles/deadlineexceedederrors?hl=en

**Comment by anbasile** [comment]
Did you already check this ?

## My bot is hitting limits, how do I avoid this?

When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors.

If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so. Consider spreading out notifications over large intervals of 8—12 hours for best results.

## How can I message all of my bot's subscribers at once?

Unfortunately, at this moment we don't have methods for sending bulk messages, e.g. notifications. We may add something along these lines in the future.

In order to avoid hitting our limits when sending out mass notifications, consider spreading them over longer intervals, e.g. 8-12 hours. The API will not allow more than ~30 messages to different users per second, if you go over that, you'll start getting 429 errors.

https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

**Comment by kercos** [comment]
this might relate to the fact that the code is not thread safe and has some latency to handle big requests (e.g., multiple boradcasting)

**Comment by kercos** [comment]
This issue has been solved, long running jobs (greater than 60 sec but less than 10min) should be done via task query https://cloud.google.com/appengine/docs/python/taskqueue/overview-push

**Comment by kercos** [comment]
This issue has been solved, long running jobs (greater than 60 sec but less than 10min) should be done via task query https://cloud.google.com/appengine/docs/python/taskqueue/overview-push
